import { test, expect, describe } from "bun:test";
import { Day07 } from "./day07";

describe("Day 7", () => {
  const day = new Day07();

  test("part one", () => {
    const input = `.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
...............`;
    const result = day.partOne(input);
    expect(result).toBe("21");
  });

  test("part two", () => {
    const input = "";
    const result = day.partTwo(input);
    // TODO: Update with expected result from example
    expect(result).toBe("Not implemented");
  });
});
